server:
  port: 10010

<<<<<<< HEAD
# 配置路由
  servlet:
    context-path: /movie

=======
>>>>>>> 搭建后台框架
# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/movie?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

<<<<<<< HEAD
# thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false

=======
>>>>>>> 搭建后台框架
# mybatis
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.movie.pojo

#logging
logging:
  level:
    com:
      movie:
<<<<<<< HEAD
        mapper: debug

=======
        mapper: debug
>>>>>>> 搭建后台框架
